# Generated by Django 6.1 on 2026-09-02 01:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('data_imports', '0006_migrate_importbatch_lifecycle_statuses'),
        ('people', '0004_normalize_person_demographic_values'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('start_at', models.DateTimeField()),
                ('end_at', models.DateTimeField(blank=True, null=True)),
                ('timezone', models.CharField(max_length=64)),
                ('location_name', models.CharField(blank=True, max_length=255)),
                ('status', models.CharField(choices=[('SCHEDULED', 'Scheduled'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled')], default='SCHEDULED', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-start_at', 'id'],
            },
        ),
        migrations.CreateModel(
            name='EventParticipation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('REGISTERED', 'Registered'), ('ATTENDED', 'Attended'), ('CANCELLED', 'Cancelled')], default='REGISTERED', max_length=20)),
                ('ticket_quantity', models.PositiveIntegerField(blank=True, null=True)),
                ('registered_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='participations', to='events.event')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='event_participations', to='people.person')),
            ],
            options={
                'ordering': ['event_id', 'person_id', 'id'],
            },
        ),
        migrations.CreateModel(
            name='ExternalEventReference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(max_length=100)),
                ('reference_type', models.CharField(choices=[('EVENT', 'Event'), ('PARTICIPATION', 'Participation')], max_length=20)),
                ('external_id', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='external_references', to='events.event')),
                ('import_record', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='event_external_references', to='data_imports.importrecord')),
                ('participation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='external_references', to='events.eventparticipation')),
            ],
        ),
        migrations.AddIndex(
            model_name='eventparticipation',
            index=models.Index(fields=['person', 'event'], name='event_part_person_event_idx'),
        ),
        migrations.AddConstraint(
            model_name='eventparticipation',
            constraint=models.UniqueConstraint(fields=('event', 'person'), name='event_participation_event_person_unique'),
        ),
        migrations.AddIndex(
            model_name='externaleventreference',
            index=models.Index(fields=['event', 'reference_type'], name='ext_event_ref_event_type_idx'),
        ),
        migrations.AddIndex(
            model_name='externaleventreference',
            index=models.Index(fields=['participation', 'reference_type'], name='ext_event_ref_part_type_idx'),
        ),
        migrations.AddConstraint(
            model_name='externaleventreference',
            constraint=models.UniqueConstraint(fields=('provider', 'reference_type', 'external_id'), name='external_event_reference_provider_type_id_unique'),
        ),
    ]
