# Generated by Django 6.1 on 2026-08-31

from django.db import migrations


CANONICAL_INTERESTS = (
    {"name": "Networking", "slug": "networking", "display_order": 10},
    {"name": "Mentoring", "slug": "mentoring", "display_order": 20},
    {"name": "Career Development", "slug": "career-development", "display_order": 30},
    {"name": "Entrepreneurship", "slug": "entrepreneurship", "display_order": 40},
    {"name": "Technology", "slug": "technology", "display_order": 50},
    {"name": "Leadership", "slug": "leadership", "display_order": 60},
    {"name": "Business Collaboration", "slug": "business-collaboration", "display_order": 70},
    {"name": "Speaking Opportunities", "slug": "speaking-opportunities", "display_order": 80},
    {"name": "Volunteering", "slug": "volunteering", "display_order": 90},
    {"name": "Professional Development", "slug": "professional-development", "display_order": 100},
    {"name": "Community Building", "slug": "community-building", "display_order": 110},
    {"name": "Investment & Funding", "slug": "investment-funding", "display_order": 120},
    {"name": "Startups", "slug": "startups", "display_order": 130},
    {"name": "Innovation", "slug": "innovation", "display_order": 140},
    {"name": "Social Impact", "slug": "social-impact", "display_order": 150},
    {"name": "Events & Workshops", "slug": "events-workshops", "display_order": 160},
    {"name": "Job Opportunities", "slug": "job-opportunities", "display_order": 170},
    {"name": "Partnerships", "slug": "partnerships", "display_order": 180},
    {"name": "Other", "slug": "other", "display_order": 190},
)


def seed_canonical_interests(apps, schema_editor):
    Interest = apps.get_model("interests", "Interest")

    for interest in CANONICAL_INTERESTS:
        existing_interest = Interest.objects.filter(slug=interest["slug"]).first()
        if existing_interest is None:
            Interest.objects.create(
                name=interest["name"],
                slug=interest["slug"],
                display_order=interest["display_order"],
                is_active=True,
            )
            continue

        existing_interest.name = interest["name"]
        existing_interest.display_order = interest["display_order"]
        existing_interest.is_active = True
        existing_interest.save(update_fields=["name", "display_order", "is_active", "updated_at"])


def noop_reverse(apps, schema_editor):
    # Reversal intentionally leaves canonical rows in place because they may already be referenced by
    # PersonInterest and should not be deleted automatically.
    return


class Migration(migrations.Migration):

    dependencies = [
        ("interests", "0001_initial"),
    ]

    operations = [
        migrations.RunPython(seed_canonical_interests, noop_reverse),
    ]
