# Generated by Django 6.1 on 2026-09-30 13:26

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0001_initial'),
        ('people', '0004_normalize_person_demographic_values'),
    ]

    operations = [
        migrations.CreateModel(
            name='CommunityAccountInvitation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('intended_email', models.EmailField(max_length=254)),
                ('token_hash', models.CharField(blank=True, max_length=64, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField()),
                ('used_at', models.DateTimeField(blank=True, null=True)),
                ('revoked_at', models.DateTimeField(blank=True, null=True)),
                ('superseded_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='community_account_invitations', to='people.person')),
            ],
            options={
                'ordering': ['-created_at', '-id'],
                'indexes': [models.Index(fields=['token_hash'], name='community_invite_token_idx'), models.Index(fields=['person', 'expires_at', 'used_at', 'revoked_at', 'superseded_at'], name='community_invite_state_idx')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('revoked_at__isnull', True), ('superseded_at__isnull', True), ('used_at__isnull', True)), fields=('person',), name='community_one_current_invitation')],
            },
        ),
    ]
