# Generated by Django 6.1 on 2026-10-02 17:38

import community.photos
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0003_communityprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='communityprofile',
            name='photo',
            field=models.ImageField(blank=True, max_length=500, null=True, upload_to=community.photos.community_profile_photo_upload_to),
        ),
    ]
