# Generated by Django 6.1 on 2026-10-04 01:19

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0007_communityprofile_directory_visible_default'),
        ('people', '0004_normalize_person_demographic_values'),
    ]

    operations = [
        migrations.CreateModel(
            name='CommunityConnection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('ACCEPTED', 'Accepted'), ('DECLINED', 'Declined'), ('DISCONNECTED', 'Disconnected')], max_length=20)),
                ('requested_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('accepted_at', models.DateTimeField(blank=True, null=True)),
                ('declined_at', models.DateTimeField(blank=True, null=True)),
                ('disconnected_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('person_high', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='community_connections_high', to='people.person')),
                ('person_low', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='community_connections_low', to='people.person')),
                ('requester', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='community_connection_requests', to='people.person')),
            ],
            options={
                'ordering': ['-updated_at', '-id'],
                'indexes': [models.Index(fields=['person_low', 'status'], name='community_conn_low_status_idx'), models.Index(fields=['person_high', 'status'], name='community_conn_high_status_idx'), models.Index(fields=['requester', 'status'], name='community_conn_req_status_idx')],
                'constraints': [models.UniqueConstraint(fields=('person_low', 'person_high'), name='community_connection_pair_unique'), models.CheckConstraint(condition=models.Q(('person_low__lt', models.F('person_high'))), name='community_connection_pair_canonical'), models.CheckConstraint(condition=models.Q(('person_low', models.F('person_high')), _negated=True), name='community_connection_no_self_pair'), models.CheckConstraint(condition=models.Q(('requester', models.F('person_low')), ('requester', models.F('person_high')), _connector='OR'), name='community_connection_requester_in_pair')],
            },
        ),
    ]
