# Generated by Django 6.1 on 2026-10-07 15:58

import community.models
import django.core.validators
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0009_communityemailchangerequest'),
        ('people', '0004_normalize_person_demographic_values'),
    ]

    operations = [
        migrations.CreateModel(
            name='CommunityPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('purpose', models.CharField(choices=[('ASK', 'Ask'), ('OFFER', 'Offer'), ('OPPORTUNITY', 'Opportunity'), ('UPDATE', 'Update')], max_length=20)),
                ('headline', models.CharField(max_length=120, validators=[community.models.validate_non_empty_text, django.core.validators.MaxLengthValidator(120)])),
                ('body', models.TextField(max_length=2000, validators=[community.models.validate_non_empty_text, django.core.validators.MaxLengthValidator(2000)])),
                ('audience', models.CharField(choices=[('ELEVATE_COMMUNITY', 'Elevate Community'), ('CONNECTIONS', 'Connections')], max_length=20)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('AUTHOR_DELETED', 'Author deleted'), ('MODERATOR_REMOVED', 'Moderator removed')], default='ACTIVE', max_length=20)),
                ('edited_at', models.DateTimeField(blank=True, null=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('removed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='community_posts', to='people.person')),
            ],
            options={
                'ordering': ['-created_at', '-id'],
                'indexes': [models.Index(fields=['status', '-created_at', '-id'], name='cpost_status_created_idx'), models.Index(fields=['purpose', 'status', '-created_at', '-id'], name='cpost_purpose_idx'), models.Index(fields=['audience', 'status', '-created_at', '-id'], name='cpost_audience_idx'), models.Index(fields=['author', 'status', '-created_at', '-id'], name='cpost_author_idx')],
            },
        ),
    ]
