# Generated by Django 6.1 on 2026-10-07 16:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0010_communitypost'),
        ('people', '0004_normalize_person_demographic_values'),
    ]

    operations = [
        migrations.CreateModel(
            name='CommunityPostIdempotencyReceipt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key_hash', models.CharField(max_length=64)),
                ('request_digest', models.CharField(max_length=64)),
                ('expires_at', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='community_post_idempotency_receipts', to='people.person')),
                ('post', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='idempotency_receipt', to='community.communitypost')),
            ],
            options={
                'indexes': [models.Index(fields=['author', 'expires_at'], name='cpost_receipt_expiry_idx')],
                'constraints': [models.UniqueConstraint(fields=('author', 'key_hash'), name='community_post_idempotency_unique')],
            },
        ),
    ]
