# Generated by Django 6.1 on 2026-10-07 16:32

import community.models
import django.core.validators
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0011_communitypostidempotencyreceipt'),
        ('people', '0004_normalize_person_demographic_values'),
    ]

    operations = [
        migrations.CreateModel(
            name='CommunityPostReply',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('body', models.TextField(max_length=1000, validators=[community.models.validate_non_empty_text, django.core.validators.MaxLengthValidator(1000)])),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('AUTHOR_DELETED', 'Author deleted'), ('MODERATOR_REMOVED', 'Moderator removed')], default='ACTIVE', max_length=20)),
                ('edited_at', models.DateTimeField(blank=True, null=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('removed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='community_post_replies', to='people.person')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='replies', to='community.communitypost')),
                ('reply_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='child_replies', to='community.communitypostreply')),
            ],
            options={
                'ordering': ['created_at', 'id'],
            },
        ),
        migrations.CreateModel(
            name='CommunityPostReplyIdempotencyReceipt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key_hash', models.CharField(max_length=64)),
                ('request_digest', models.CharField(max_length=64)),
                ('expires_at', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='community_post_reply_idempotency_receipts', to='people.person')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reply_idempotency_receipts', to='community.communitypost')),
                ('reply', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='idempotency_receipt', to='community.communitypostreply')),
            ],
        ),
        migrations.AddIndex(
            model_name='communitypostreply',
            index=models.Index(fields=['post', 'status', 'created_at', 'id'], name='cpreply_post_status_idx'),
        ),
        migrations.AddIndex(
            model_name='communitypostreply',
            index=models.Index(fields=['author', 'status', 'created_at', 'id'], name='cpreply_author_status_idx'),
        ),
        migrations.AddIndex(
            model_name='communitypostreplyidempotencyreceipt',
            index=models.Index(fields=['author', 'post', 'expires_at'], name='cpreply_receipt_expiry_idx'),
        ),
        migrations.AddConstraint(
            model_name='communitypostreplyidempotencyreceipt',
            constraint=models.UniqueConstraint(fields=('author', 'post', 'key_hash'), name='community_reply_idempotency_unique'),
        ),
    ]
