# Generated by Django 6.1 on 2026-10-07 17:06

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0012_communitypostreply_and_more'),
        ('people', '0004_normalize_person_demographic_values'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CommunityContentReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('reason', models.CharField(choices=[('OFF_TOPIC', 'Off topic'), ('SPAM_OR_EXCESSIVE_PROMOTION', 'Spam or excessive promotion'), ('INAPPROPRIATE_OR_ABUSIVE', 'Inappropriate or abusive'), ('MISLEADING_OR_SUSPICIOUS', 'Misleading or suspicious'), ('OTHER', 'Other')], max_length=40)),
                ('details', models.TextField(blank=True, max_length=1000)),
                ('status', models.CharField(choices=[('OPEN', 'Open'), ('DISMISSED', 'Dismissed'), ('RESOLVED', 'Resolved')], default='OPEN', max_length=20)),
                ('resolution', models.TextField(blank=True, max_length=1000)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('moderator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='community_moderated_reports', to=settings.AUTH_USER_MODEL)),
                ('post', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='content_reports', to='community.communitypost')),
                ('reply', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='content_reports', to='community.communitypostreply')),
                ('reporter', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='community_content_reports', to='people.person')),
            ],
            options={
                'ordering': ['-created_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='CommunityModerationAction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('action', models.CharField(choices=[('DISMISSED', 'Report dismissed'), ('CONTENT_REMOVED', 'Content removed'), ('CONTENT_RESTORED', 'Content restored')], max_length=30)),
                ('resolution', models.TextField(blank=True, max_length=1000)),
                ('occurred_at', models.DateTimeField(auto_now_add=True)),
                ('moderator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='community_moderation_actions', to=settings.AUTH_USER_MODEL)),
                ('post', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='moderation_actions', to='community.communitypost')),
                ('reply', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='moderation_actions', to='community.communitypostreply')),
                ('report', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='moderation_actions', to='community.communitycontentreport')),
            ],
            options={
                'ordering': ['-occurred_at', '-id'],
            },
        ),
        migrations.AddIndex(
            model_name='communitycontentreport',
            index=models.Index(fields=['status', 'created_at'], name='comm_report_status_created'),
        ),
        migrations.AddConstraint(
            model_name='communitycontentreport',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('post__isnull', False), ('reply__isnull', True)), models.Q(('post__isnull', True), ('reply__isnull', False)), _connector='OR'), name='community_report_exactly_one_target'),
        ),
        migrations.AddConstraint(
            model_name='communitycontentreport',
            constraint=models.UniqueConstraint(condition=models.Q(('post__isnull', False), ('status', 'OPEN')), fields=('reporter', 'post'), name='community_report_open_post_unique'),
        ),
        migrations.AddConstraint(
            model_name='communitycontentreport',
            constraint=models.UniqueConstraint(condition=models.Q(('reply__isnull', False), ('status', 'OPEN')), fields=('reporter', 'reply'), name='community_report_open_reply_unique'),
        ),
        migrations.AddConstraint(
            model_name='communitymoderationaction',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('post__isnull', False), ('reply__isnull', True)), models.Q(('post__isnull', True), ('reply__isnull', False)), _connector='OR'), name='community_moderation_action_exactly_one_target'),
        ),
    ]
