# Generated by Django 6.1 on 2026-08-30 11:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('people', '0002_person_record_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='Membership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('FORMER', 'Former')], max_length=20)),
                ('joined_at', models.DateField()),
                ('ended_at', models.DateField(blank=True, null=True)),
                ('membership_source', models.CharField(choices=[('WEBSITE_FORM', 'Website form'), ('STAFF', 'Staff'), ('COMMUNITY_PLATFORM', 'Community platform'), ('OTHER', 'Other')], max_length=30)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('person', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='membership', to='people.person')),
            ],
            options={
                'ordering': ['-joined_at', 'id'],
            },
        ),
    ]
