# Generated by Django 6.1 on 2026-09-01 23:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('memberships', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='membership',
            name='membership_source',
            field=models.CharField(choices=[('WEBSITE_FORM', 'Website form'), ('MEMBERSHIP_FORM', 'Membership Form'), ('STAFF', 'Staff'), ('COMMUNITY_PLATFORM', 'Community platform'), ('OTHER', 'Other')], max_length=30),
        ),
    ]
