# Generated by Django 6.1 on 2026-09-15 12:11

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('external_references', '0001_initial'),
        ('people', '0004_normalize_person_demographic_values'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExternalPersonSyncJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(max_length=100)),
                ('job_type', models.CharField(max_length=100)),
                ('source_event_id', models.PositiveBigIntegerField()),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('PROCESSING', 'Processing'), ('SUCCEEDED', 'Succeeded'), ('FAILED', 'Failed')], default='PENDING', max_length=20)),
                ('available_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('attempts', models.PositiveIntegerField(default=0)),
                ('max_attempts', models.PositiveIntegerField(default=5)),
                ('locked_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('last_error_code', models.CharField(blank=True, max_length=100, null=True)),
                ('last_error_message', models.CharField(blank=True, max_length=500, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='external_sync_jobs', to='people.person')),
            ],
            options={
                'ordering': ['available_at', 'id'],
                'indexes': [models.Index(fields=['provider', 'status', 'available_at'], name='ext_sync_job_ready_idx'), models.Index(fields=['person', 'provider', 'job_type'], name='ext_sync_job_person_idx')],
                'constraints': [models.UniqueConstraint(fields=('provider', 'job_type', 'source_event_id'), name='external_sync_job_provider_type_event_unique')],
            },
        ),
    ]
