# Generated by Django 6.1 on 2026-09-25 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('external_references', '0002_externalpersonsyncjob'),
    ]

    operations = [
        migrations.AddField(
            model_name='externalpersonsyncjob',
            name='previous_email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='externalpersonsyncjob',
            name='requested_email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
