# Generated by Django 6.1 on 2026-08-31

from django.db import migrations


CANONICAL_TAGS = (
    {"name": "Potential Speaker", "slug": "potential-speaker", "display_order": 10},
    {"name": "Potential Mentor", "slug": "potential-mentor", "display_order": 20},
    {"name": "Potential Volunteer", "slug": "potential-volunteer", "display_order": 30},
    {"name": "Partner Lead", "slug": "partner-lead", "display_order": 40},
    {"name": "Sponsor Contact", "slug": "sponsor-contact", "display_order": 50},
    {"name": "Follow-up Required", "slug": "follow-up-required", "display_order": 60},
    {"name": "Founding Member", "slug": "founding-member", "display_order": 70},
    {"name": "VIP", "slug": "vip", "display_order": 80},
    {"name": "Other", "slug": "other", "display_order": 90},
)


def seed_canonical_tags(apps, schema_editor):
    Tag = apps.get_model("tags", "Tag")

    for tag in CANONICAL_TAGS:
        existing_tag = Tag.objects.filter(slug=tag["slug"]).first()
        if existing_tag is None:
            Tag.objects.create(
                name=tag["name"],
                slug=tag["slug"],
                display_order=tag["display_order"],
                is_active=True,
            )
            continue

        existing_tag.name = tag["name"]
        existing_tag.display_order = tag["display_order"]
        existing_tag.is_active = True
        existing_tag.save(update_fields=["name", "display_order", "is_active", "updated_at"])


def noop_reverse(apps, schema_editor):
    # Reversal intentionally leaves canonical rows in place because they may already be referenced by
    # PersonTag and should not be deleted automatically.
    return


class Migration(migrations.Migration):

    dependencies = [
        ("tags", "0001_initial"),
    ]

    operations = [
        migrations.RunPython(seed_canonical_tags, noop_reverse),
    ]
