# Generated by Django 6.1 on 2026-08-31 11:35

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('LOGIN_SUCCEEDED', 'Login succeeded'), ('LOGIN_FAILED', 'Login failed'), ('LOGOUT', 'Logout'), ('MEMBERSHIP_CREATED', 'Membership created'), ('MEMBERSHIP_ENDED', 'Membership ended'), ('PROFESSIONAL_PROFILE_CREATED', 'Professional profile created'), ('PROFESSIONAL_PROFILE_UPDATED', 'Professional profile updated'), ('SKILL_ASSIGNED', 'Skill assigned'), ('SKILL_REMOVED', 'Skill removed'), ('INTEREST_ASSIGNED', 'Interest assigned'), ('INTEREST_REMOVED', 'Interest removed'), ('TAG_ASSIGNED', 'Tag assigned'), ('TAG_REACTIVATED', 'Tag reactivated'), ('TAG_REMOVED', 'Tag removed'), ('NOTE_CREATED', 'Note created'), ('NOTE_UPDATED', 'Note updated'), ('NOTE_ARCHIVED', 'Note archived'), ('NOTE_RESTORED', 'Note restored'), ('STAFF_ROLE_ASSIGNED', 'Staff role assigned'), ('STAFF_ROLE_REVOKED', 'Staff role revoked'), ('ACCOUNT_DISABLED', 'Account disabled'), ('ACCOUNT_REENABLED', 'Account reenabled'), ('PASSWORD_CHANGED', 'Password changed'), ('PASSWORD_RESET', 'Password reset')], db_index=True, max_length=100)),
                ('entity_type', models.CharField(max_length=100)),
                ('entity_id', models.CharField(blank=True, max_length=255, null=True)),
                ('changes', models.JSONField(blank=True, default=dict)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('request_id', models.CharField(blank=True, max_length=255, null=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('occurred_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('actor_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='audit_events', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-occurred_at', '-id'],
                'indexes': [models.Index(fields=['entity_type', 'entity_id'], name='audit_event_entity_idx')],
            },
        ),
    ]
