# Generated by Django 6.1 on 2026-09-01 23:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0004_alter_auditevent_action'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditevent',
            name='action',
            field=models.CharField(choices=[('LOGIN_SUCCEEDED', 'Login succeeded'), ('LOGIN_FAILED', 'Login failed'), ('LOGOUT', 'Logout'), ('PERSON_CREATED', 'Person created'), ('PERSON_UPDATED', 'Person updated'), ('PERSON_ARCHIVED', 'Person archived'), ('PERSON_RESTORED', 'Person restored'), ('MEMBERSHIP_CREATED', 'Membership created'), ('MEMBERSHIP_ENDED', 'Membership ended'), ('PROFESSIONAL_PROFILE_CREATED', 'Professional profile created'), ('PROFESSIONAL_PROFILE_UPDATED', 'Professional profile updated'), ('SKILL_ASSIGNED', 'Skill assigned'), ('SKILL_REMOVED', 'Skill removed'), ('INTEREST_ASSIGNED', 'Interest assigned'), ('INTEREST_REMOVED', 'Interest removed'), ('TAG_ASSIGNED', 'Tag assigned'), ('TAG_REACTIVATED', 'Tag reactivated'), ('TAG_REMOVED', 'Tag removed'), ('NOTE_CREATED', 'Note created'), ('NOTE_UPDATED', 'Note updated'), ('NOTE_ARCHIVED', 'Note archived'), ('NOTE_RESTORED', 'Note restored'), ('STAFF_ROLE_ASSIGNED', 'Staff role assigned'), ('STAFF_ROLE_REACTIVATED', 'Staff role reactivated'), ('STAFF_ROLE_REVOKED', 'Staff role revoked'), ('ACCOUNT_DISABLED', 'Account disabled'), ('ACCOUNT_REENABLED', 'Account reenabled'), ('PASSWORD_CHANGED', 'Password changed'), ('PASSWORD_RESET', 'Password reset'), ('IMPORT_RECORD_MATCH_CONFIRMED', 'Import record match confirmed'), ('IMPORT_RECORD_CREATE_NEW_CONFIRMED', 'Import record create-new confirmed'), ('IMPORT_BATCH_IMPORTED', 'Import batch imported')], db_index=True, max_length=100),
        ),
    ]
