# Generated by Django 6.1 on 2026-09-25 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0008_alter_auditevent_action'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditevent',
            name='action',
            field=models.CharField(choices=[('LOGIN_SUCCEEDED', 'Login succeeded'), ('LOGIN_FAILED', 'Login failed'), ('LOGOUT', 'Logout'), ('PERSON_CREATED', 'Person created'), ('PERSON_UPDATED', 'Person updated'), ('PERSON_ARCHIVED', 'Person archived'), ('PERSON_RESTORED', 'Person restored'), ('MEMBERSHIP_CREATED', 'Membership created'), ('MEMBERSHIP_ENDED', 'Membership ended'), ('PROFESSIONAL_PROFILE_CREATED', 'Professional profile created'), ('PROFESSIONAL_PROFILE_UPDATED', 'Professional profile updated'), ('SKILL_ASSIGNED', 'Skill assigned'), ('SKILL_REMOVED', 'Skill removed'), ('INTEREST_ASSIGNED', 'Interest assigned'), ('INTEREST_REMOVED', 'Interest removed'), ('TAG_ASSIGNED', 'Tag assigned'), ('TAG_REACTIVATED', 'Tag reactivated'), ('TAG_REMOVED', 'Tag removed'), ('NOTE_CREATED', 'Note created'), ('NOTE_UPDATED', 'Note updated'), ('NOTE_ARCHIVED', 'Note archived'), ('NOTE_RESTORED', 'Note restored'), ('STAFF_ROLE_ASSIGNED', 'Staff role assigned'), ('STAFF_ROLE_REACTIVATED', 'Staff role reactivated'), ('STAFF_ROLE_REVOKED', 'Staff role revoked'), ('ACCOUNT_DISABLED', 'Account disabled'), ('ACCOUNT_REENABLED', 'Account reenabled'), ('PASSWORD_CHANGED', 'Password changed'), ('PASSWORD_RESET', 'Password reset'), ('IMPORT_RECORD_MATCH_CONFIRMED', 'Import record match confirmed'), ('IMPORT_RECORD_CREATE_NEW_CONFIRMED', 'Import record create-new confirmed'), ('IMPORT_BATCH_IMPORTED', 'Import batch imported'), ('EXTERNAL_PERSON_REFERENCE_LINKED', 'External person reference linked'), ('EXTERNAL_PERSON_REFERENCE_REACTIVATED', 'External person reference reactivated'), ('EXTERNAL_PERSON_REFERENCE_REVOKED', 'External person reference revoked'), ('MARKETING_PREFERENCE_OPTED_IN', 'Marketing preference opted in'), ('MARKETING_PREFERENCE_OPTED_OUT', 'Marketing preference opted out'), ('CAMPAIGN_CREATED', 'Campaign created'), ('CAMPAIGN_PREPARATION_STARTED', 'Campaign preparation started'), ('CAMPAIGN_RECIPIENT_SNAPSHOT_CREATED', 'Campaign recipient snapshot created'), ('CAMPAIGN_PREPARATION_SNAPSHOT_READY', 'Campaign preparation snapshot ready'), ('CAMPAIGN_PROVIDER_PREPARATION_STARTED', 'Campaign provider preparation started'), ('CAMPAIGN_BREVO_LIST_CREATED', 'Campaign Brevo list created'), ('CAMPAIGN_LIST_POPULATED', 'Campaign list populated'), ('CAMPAIGN_BREVO_DRAFT_CREATED', 'Campaign Brevo draft created'), ('CAMPAIGN_PROVIDER_PREPARATION_COMPLETED', 'Campaign provider preparation completed'), ('CAMPAIGN_RECONCILIATION_REQUIRED', 'Campaign reconciliation required'), ('CAMPAIGN_PROVIDER_FAILURE', 'Campaign provider failure'), ('CAMPAIGN_PROVIDER_RETRY', 'Campaign provider retry')], db_index=True, max_length=100),
        ),
    ]
