# Generated by Django 6.1 on 2026-08-31 23:14

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('people', '0002_person_record_type'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ImportBatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_type', models.CharField(choices=[('MEMBERSHIP_FORM', 'Membership Form'), ('EVENTBRITE', 'Eventbrite')], max_length=32)),
                ('source_filename', models.CharField(max_length=255)),
                ('source_fingerprint', models.CharField(db_index=True, max_length=64)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('PROCESSING', 'Processing'), ('READY_FOR_REVIEW', 'Ready for review'), ('COMMITTING', 'Committing'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed')], default='PENDING', max_length=32)),
                ('started_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='import_batches_created', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='ImportRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_row_identifier', models.CharField(max_length=255)),
                ('source_fingerprint', models.CharField(db_index=True, max_length=64)),
                ('raw_data', models.JSONField(default=dict)),
                ('normalized_data', models.JSONField(default=dict)),
                ('status', models.CharField(choices=[('STAGED', 'Staged'), ('INVALID', 'Invalid'), ('ANALYZED', 'Analyzed'), ('REVIEW_REQUIRED', 'Review required'), ('RESOLVED', 'Resolved'), ('COMMITTED', 'Committed'), ('SKIPPED', 'Skipped'), ('FAILED', 'Failed')], default='STAGED', max_length=32)),
                ('outcome', models.CharField(blank=True, choices=[('CREATED', 'Created'), ('MATCHED', 'Matched'), ('UPDATED', 'Updated'), ('SKIPPED', 'Skipped')], max_length=32, null=True)),
                ('resolution_method', models.CharField(blank=True, choices=[('AUTO_MATCH', 'Automatic match'), ('STAFF_MATCH', 'Staff match'), ('STAFF_CREATE_NEW', 'Staff create new'), ('NO_MATCH', 'No match'), ('NOT_RESOLVED', 'Not resolved')], max_length=32, null=True)),
                ('resolution_reason', models.TextField(blank=True, null=True)),
                ('match_candidates', models.JSONField(blank=True, default=list)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('committed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='records', to='data_imports.importbatch')),
                ('resolved_person', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='import_records_resolved', to='people.person')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='import_records_reviewed', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['batch_id', 'source_row_identifier', 'id'],
            },
        ),
        migrations.AddIndex(
            model_name='importbatch',
            index=models.Index(fields=['source_type', 'status'], name='import_batch_source_status_idx'),
        ),
        migrations.AddIndex(
            model_name='importrecord',
            index=models.Index(fields=['batch', 'status'], name='import_record_batch_status_idx'),
        ),
        migrations.AddConstraint(
            model_name='importrecord',
            constraint=models.UniqueConstraint(fields=('batch', 'source_row_identifier'), name='import_record_batch_row_identifier_unique'),
        ),
    ]
