# Generated by Django 6.1 on 2026-08-31 23:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_imports', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='importrecord',
            name='validation_errors',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name='importbatch',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('PROCESSING', 'Processing'), ('STAGED', 'Staged'), ('READY_FOR_REVIEW', 'Ready for review'), ('COMMITTING', 'Committing'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed')], default='PENDING', max_length=32),
        ),
    ]
