# Generated by Django 6.1 on 2026-08-31 23:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_imports', '0002_importrecord_validation_errors_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='importrecord',
            name='match_evidence',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name='importbatch',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('PROCESSING', 'Processing'), ('STAGED', 'Staged'), ('ANALYZED', 'Analyzed'), ('READY_FOR_REVIEW', 'Ready for review'), ('COMMITTING', 'Committing'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed')], default='PENDING', max_length=32),
        ),
    ]
