# Generated by Django 6.1 on 2026-09-01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("data_imports", "0003_importrecord_match_evidence_alter_importbatch_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="importbatch",
            name="status",
            field=models.CharField(
                choices=[
                    ("PENDING", "Pending"),
                    ("PROCESSING", "Processing"),
                    ("STAGED", "Staged"),
                    ("ANALYZED", "Analyzed"),
                    ("READY_FOR_REVIEW", "Ready for review"),
                    ("READY_TO_COMMIT", "Ready to commit"),
                    ("COMMITTING", "Committing"),
                    ("COMPLETED", "Completed"),
                    ("FAILED", "Failed"),
                ],
                default="PENDING",
                max_length=32,
            ),
        ),
    ]
