# Generated by Django 6.1 on 2026-09-01 23:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_imports', '0004_alter_importbatch_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='importbatch',
            name='status',
            field=models.CharField(choices=[('PROCESSING', 'Processing'), ('READY_FOR_REVIEW', 'Ready for review'), ('READY_FOR_IMPORT', 'Ready for import'), ('IMPORTED', 'Imported'), ('FAILED', 'Failed')], default='PROCESSING', max_length=32),
        ),
    ]
