# Generated by Django 6.1 on 2026-09-02 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_imports', '0006_migrate_importbatch_lifecycle_statuses'),
    ]

    operations = [
        migrations.AlterField(
            model_name='importbatch',
            name='status',
            field=models.CharField(choices=[('PROCESSING', 'Processing'), ('STAGED', 'Staged'), ('READY_FOR_REVIEW', 'Ready for review'), ('READY_FOR_IMPORT', 'Ready for import'), ('IMPORTED', 'Imported'), ('FAILED', 'Failed')], default='PROCESSING', max_length=32),
        ),
    ]
