# Generated by Django 6.1 on 2026-08-29 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='record_type',
            field=models.CharField(choices=[('BUSINESS', 'Business'), ('TECHNICAL', 'Technical')], default='BUSINESS', max_length=20),
        ),
    ]
