# Generated by Django 6.1 on 2026-09-01 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0002_person_record_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='age_range',
            field=models.CharField(blank=True, choices=[('UNDER_25', 'Under 25'), ('25_29', '25 - 29'), ('30_34', '30 - 34'), ('35_39', '35 - 39'), ('40_45', '40 - 45'), ('OVER_45', 'Over 45')], max_length=100),
        ),
        migrations.AlterField(
            model_name='person',
            name='gender',
            field=models.CharField(blank=True, choices=[('MALE', 'Male'), ('FEMALE', 'Female'), ('NON_BINARY', 'Non-Binary'), ('TRANSGENDER', 'Transgender'), ('OTHER', 'Other')], max_length=100),
        ),
    ]
