# Generated by Django 6.1 on 2026-09-25 19:04

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('people', '0004_normalize_person_demographic_values'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Campaign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('PREPARING', 'Preparing'), ('SNAPSHOT_READY', 'CRM snapshot ready'), ('PREPARED', 'Prepared'), ('RECONCILIATION_REQUIRED', 'Reconciliation required'), ('PROVIDER_FAILED', 'Provider failed'), ('CONSENT_ACTION_REQUIRED', 'Consent action required')], db_index=True, default='DRAFT', max_length=40)),
                ('audience_selection', models.JSONField(default=dict)),
                ('audience_ordering', models.CharField(default='last_name', max_length=40)),
                ('audience_schema_version', models.PositiveSmallIntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_campaigns', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='CampaignPreparation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attempt_number', models.PositiveIntegerField()),
                ('status', models.CharField(choices=[('PREPARING', 'Preparing'), ('SNAPSHOT_READY', 'CRM snapshot ready'), ('FAILED', 'Failed')], db_index=True, default='PREPARING', max_length=30)),
                ('started_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('selected_count', models.PositiveIntegerField(default=0)),
                ('included_count', models.PositiveIntegerField(default=0)),
                ('excluded_count', models.PositiveIntegerField(default=0)),
                ('brevo_list_id', models.PositiveBigIntegerField(blank=True, null=True)),
                ('brevo_campaign_id', models.PositiveBigIntegerField(blank=True, null=True)),
                ('brevo_editor_url', models.URLField(blank=True, max_length=1000, null=True)),
                ('provider_error_code', models.CharField(blank=True, max_length=100, null=True)),
                ('provider_error_message', models.CharField(blank=True, max_length=500, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='preparations', to='campaigns.campaign')),
            ],
            options={
                'ordering': ['-attempt_number', '-id'],
            },
        ),
        migrations.AddField(
            model_name='campaign',
            name='current_preparation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='current_for_campaigns', to='campaigns.campaignpreparation'),
        ),
        migrations.CreateModel(
            name='CampaignRecipientSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_snapshot', models.EmailField(blank=True, max_length=254)),
                ('first_name_snapshot', models.CharField(max_length=150)),
                ('last_name_snapshot', models.CharField(max_length=150)),
                ('consent_state_snapshot', models.CharField(max_length=20)),
                ('decision', models.CharField(choices=[('INCLUDED', 'Included'), ('EXCLUDED', 'Excluded')], max_length=20)),
                ('exclusion_reason', models.CharField(blank=True, max_length=50, null=True)),
                ('captured_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('brevo_contact_id', models.PositiveBigIntegerField(blank=True, null=True)),
                ('provider_outcome', models.CharField(blank=True, max_length=100, null=True)),
                ('provider_error_code', models.CharField(blank=True, max_length=100, null=True)),
                ('provider_error_message', models.CharField(blank=True, max_length=500, null=True)),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='campaign_recipient_snapshots', to='people.person')),
                ('preparation', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='recipient_snapshots', to='campaigns.campaignpreparation')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.AddConstraint(
            model_name='campaignpreparation',
            constraint=models.UniqueConstraint(fields=('campaign', 'attempt_number'), name='campaign_prep_campaign_attempt_unique'),
        ),
        migrations.AddIndex(
            model_name='campaignrecipientsnapshot',
            index=models.Index(fields=['preparation', 'decision'], name='camp_snap_prep_decision_idx'),
        ),
        migrations.AddConstraint(
            model_name='campaignrecipientsnapshot',
            constraint=models.UniqueConstraint(fields=('preparation', 'person'), name='campaign_snapshot_preparation_person_unique'),
        ),
    ]
