# Generated by Django 6.1 on 2026-09-25 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campaign',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'Draft'), ('PREPARING', 'Preparing'), ('SNAPSHOT_READY', 'CRM snapshot ready'), ('PREPARED', 'Prepared'), ('RECONCILIATION_REQUIRED', 'Reconciliation required'), ('PROVIDER_FAILED', 'Provider failed'), ('NO_READY_RECIPIENTS', 'No ready recipients')], db_index=True, default='DRAFT', max_length=40),
        ),
        migrations.AlterField(
            model_name='campaignpreparation',
            name='status',
            field=models.CharField(choices=[('PREPARING', 'Preparing'), ('SNAPSHOT_READY', 'CRM snapshot ready'), ('FAILED', 'Failed'), ('PROVIDER_PREPARING', 'Provider preparing'), ('PREPARED', 'Prepared'), ('RECONCILIATION_REQUIRED', 'Reconciliation required'), ('PROVIDER_FAILED', 'Provider failed'), ('NO_READY_RECIPIENTS', 'No ready recipients')], db_index=True, default='PREPARING', max_length=30),
        ),
    ]
