# Generated by Django 6.1 on 2026-08-31

from django.db import migrations


CANONICAL_SKILLS = (
    {"name": "Accounting", "slug": "accounting", "display_order": 10},
    {"name": "Business Development", "slug": "business-development", "display_order": 20},
    {"name": "Coaching", "slug": "coaching", "display_order": 30},
    {"name": "Content Creation", "slug": "content-creation", "display_order": 40},
    {"name": "Customer Service", "slug": "customer-service", "display_order": 50},
    {"name": "Data Analysis", "slug": "data-analysis", "display_order": 60},
    {"name": "Digital Marketing", "slug": "digital-marketing", "display_order": 70},
    {"name": "Event Management", "slug": "event-management", "display_order": 80},
    {"name": "Finance", "slug": "finance", "display_order": 90},
    {"name": "Graphic Design", "slug": "graphic-design", "display_order": 100},
    {"name": "Leadership", "slug": "leadership", "display_order": 110},
    {"name": "Marketing", "slug": "marketing", "display_order": 120},
    {"name": "Mentoring", "slug": "mentoring", "display_order": 130},
    {"name": "Operations Management", "slug": "operations-management", "display_order": 140},
    {"name": "Photography", "slug": "photography", "display_order": 150},
    {"name": "Project Management", "slug": "project-management", "display_order": 160},
    {"name": "Public Speaking", "slug": "public-speaking", "display_order": 170},
    {"name": "Recruitment", "slug": "recruitment", "display_order": 180},
    {"name": "Sales", "slug": "sales", "display_order": 190},
    {"name": "Social Media Management", "slug": "social-media-management", "display_order": 200},
    {"name": "Software Development", "slug": "software-development", "display_order": 210},
    {"name": "Strategy", "slug": "strategy", "display_order": 220},
    {"name": "Teaching & Training", "slug": "teaching-training", "display_order": 230},
    {"name": "Video Production", "slug": "video-production", "display_order": 240},
    {"name": "Web Design", "slug": "web-design", "display_order": 250},
    {"name": "Writing & Editing", "slug": "writing-editing", "display_order": 260},
    {"name": "Other", "slug": "other", "display_order": 270},
)


def seed_canonical_skills(apps, schema_editor):
    Skill = apps.get_model("skills", "Skill")

    for skill in CANONICAL_SKILLS:
        existing_skill = Skill.objects.filter(slug=skill["slug"]).first()
        if existing_skill is None:
            Skill.objects.create(
                name=skill["name"],
                slug=skill["slug"],
                display_order=skill["display_order"],
                is_active=True,
            )
            continue

        existing_skill.name = skill["name"]
        existing_skill.display_order = skill["display_order"]
        existing_skill.is_active = True
        existing_skill.save(update_fields=["name", "display_order", "is_active", "updated_at"])


def noop_reverse(apps, schema_editor):
    # Reversal intentionally leaves canonical rows in place because they may already be referenced by
    # PersonSkill and should not be deleted automatically.
    return


class Migration(migrations.Migration):

    dependencies = [
        ("skills", "0001_initial"),
    ]

    operations = [
        migrations.RunPython(seed_canonical_skills, noop_reverse),
    ]
