# Generated by Django 6.1 on 2026-08-30

from django.db import migrations, models


CANONICAL_INDUSTRIES = (
    {"name": "Accounting", "slug": "accounting", "display_order": 10},
    {"name": "Advertising & Marketing", "slug": "advertising-marketing", "display_order": 20},
    {"name": "Architecture & Design", "slug": "architecture-design", "display_order": 30},
    {"name": "Arts & Creative", "slug": "arts-creative", "display_order": 40},
    {"name": "Automotive", "slug": "automotive", "display_order": 50},
    {"name": "Banking & Financial Services", "slug": "banking-financial-services", "display_order": 60},
    {"name": "Construction", "slug": "construction", "display_order": 70},
    {"name": "Consulting", "slug": "consulting", "display_order": 80},
    {"name": "Education", "slug": "education", "display_order": 90},
    {"name": "Energy & Utilities", "slug": "energy-utilities", "display_order": 100},
    {"name": "Engineering", "slug": "engineering", "display_order": 110},
    {"name": "Entertainment & Media", "slug": "entertainment-media", "display_order": 120},
    {"name": "Fashion & Beauty", "slug": "fashion-beauty", "display_order": 130},
    {"name": "Food & Hospitality", "slug": "food-hospitality", "display_order": 140},
    {"name": "Government & Public Sector", "slug": "government-public-sector", "display_order": 150},
    {"name": "Healthcare", "slug": "healthcare", "display_order": 160},
    {"name": "Insurance", "slug": "insurance", "display_order": 170},
    {"name": "Legal", "slug": "legal", "display_order": 180},
    {"name": "Manufacturing", "slug": "manufacturing", "display_order": 190},
    {"name": "Nonprofit & Charity", "slug": "nonprofit-charity", "display_order": 200},
    {"name": "Property & Real Estate", "slug": "property-real-estate", "display_order": 210},
    {"name": "Retail & E-commerce", "slug": "retail-e-commerce", "display_order": 220},
    {"name": "Science & Research", "slug": "science-research", "display_order": 230},
    {"name": "Sports & Fitness", "slug": "sports-fitness", "display_order": 240},
    {"name": "Technology", "slug": "technology", "display_order": 250},
    {"name": "Telecommunications", "slug": "telecommunications", "display_order": 260},
    {"name": "Transport & Logistics", "slug": "transport-logistics", "display_order": 270},
    {"name": "Travel & Tourism", "slug": "travel-tourism", "display_order": 280},
    {"name": "Other", "slug": "other", "display_order": 290},
)

CAREER_STAGE_VALUES = {
    "STUDENT",
    "EARLY_CAREER",
    "MID_CAREER",
    "SENIOR",
    "LEADERSHIP",
    "FOUNDER_BUSINESS_OWNER",
    "OTHER",
}


def validate_existing_career_stage_values(apps, schema_editor):
    ProfessionalProfile = apps.get_model("professional_profiles", "ProfessionalProfile")

    invalid_rows = list(
        ProfessionalProfile.objects.exclude(career_stage__isnull=True)
        .exclude(career_stage="")
        .exclude(career_stage__in=CAREER_STAGE_VALUES)
        .values_list("id", "career_stage")
    )
    if invalid_rows:
        details = ", ".join(f"id={row_id}:{career_stage}" for row_id, career_stage in invalid_rows[:10])
        raise RuntimeError(
            "Unsupported ProfessionalProfile.career_stage values exist and must be corrected before "
            f"applying this migration: {details}"
        )


def seed_canonical_industries(apps, schema_editor):
    Industry = apps.get_model("professional_profiles", "Industry")

    for industry in CANONICAL_INDUSTRIES:
        Industry.objects.update_or_create(
            slug=industry["slug"],
            defaults={
                "name": industry["name"],
                "display_order": industry["display_order"],
                "is_active": True,
            },
        )


def noop_reverse(apps, schema_editor):
    # Reversal intentionally leaves canonical rows in place because they may already be referenced by
    # ProfessionalProfile.industry and should not be deleted automatically.
    return


class Migration(migrations.Migration):

    dependencies = [
        ("professional_profiles", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="professionalprofile",
            name="career_stage",
            field=models.CharField(
                blank=True,
                choices=[
                    ("STUDENT", "Student"),
                    ("EARLY_CAREER", "Early Career"),
                    ("MID_CAREER", "Mid Career"),
                    ("SENIOR", "Senior"),
                    ("LEADERSHIP", "Leadership"),
                    ("FOUNDER_BUSINESS_OWNER", "Founder / Business Owner"),
                    ("OTHER", "Other"),
                ],
                max_length=255,
                null=True,
            ),
        ),
        migrations.RunPython(validate_existing_career_stage_values, noop_reverse),
        migrations.RunPython(seed_canonical_industries, noop_reverse),
    ]
