# Generated by Django 6.1 on 2026-09-30 13:27

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('community', '0002_communityaccountinvitation'),
    ]

    operations = [
        migrations.CreateModel(
            name='TransactionalEmailJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('template_id', models.CharField(max_length=100)),
                ('recipient_email', models.EmailField(max_length=254)),
                ('recipient_name', models.CharField(blank=True, max_length=255)),
                ('first_name', models.CharField(max_length=150)),
                ('expires_in_hours', models.PositiveIntegerField()),
                ('job_type', models.CharField(choices=[('COMMUNITY_ACTIVATION', 'Community activation')], default='COMMUNITY_ACTIVATION', max_length=50)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('PROCESSING', 'Processing'), ('SENT', 'Sent'), ('FAILED', 'Failed'), ('DELIVERY_UNCERTAIN', 'Delivery uncertain'), ('CANCELLED', 'Cancelled')], default='PENDING', max_length=20)),
                ('available_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('attempts', models.PositiveIntegerField(default=0)),
                ('max_attempts', models.PositiveIntegerField(default=5)),
                ('locked_at', models.DateTimeField(blank=True, null=True)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('provider_message_id', models.CharField(blank=True, max_length=255)),
                ('last_error_code', models.CharField(blank=True, max_length=100)),
                ('last_error_message', models.CharField(blank=True, max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('invitation', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='transactional_email_job', to='community.communityaccountinvitation')),
            ],
            options={
                'ordering': ['available_at', 'id'],
                'indexes': [models.Index(fields=['status', 'available_at'], name='tx_email_job_ready_idx'), models.Index(fields=['job_type', 'status'], name='tx_email_job_type_idx')],
            },
        ),
    ]
