# Generated by Django 6.1 on 2026-10-06 17:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0009_communityemailchangerequest'),
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='transactionalemailjob',
            name='email_change_request',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='transactional_email_job', to='community.communityemailchangerequest'),
        ),
        migrations.AddField(
            model_name='transactionalemailjob',
            name='expires_in_minutes',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='transactionalemailjob',
            name='invitation',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='transactional_email_job', to='community.communityaccountinvitation'),
        ),
        migrations.AlterField(
            model_name='transactionalemailjob',
            name='job_type',
            field=models.CharField(choices=[('COMMUNITY_ACTIVATION', 'Community activation'), ('COMMUNITY_EMAIL_CHANGE', 'Community email change verification')], default='COMMUNITY_ACTIVATION', max_length=50),
        ),
        migrations.AddConstraint(
            model_name='transactionalemailjob',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('email_change_request__isnull', True), ('invitation__isnull', False)), models.Q(('email_change_request__isnull', False), ('invitation__isnull', True)), _connector='OR'), name='transactional_email_job_single_resource'),
        ),
    ]
