# Generated by Django 6.1 on 2026-10-06 18:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0009_communityemailchangerequest'),
        ('notifications', '0002_transactionalemailjob_email_change_request_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transactionalemailjob',
            name='email_change_request',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='transactional_email_job', to='community.communityemailchangerequest'),
        ),
        migrations.AlterField(
            model_name='transactionalemailjob',
            name='job_type',
            field=models.CharField(choices=[('COMMUNITY_ACTIVATION', 'Community activation'), ('COMMUNITY_EMAIL_CHANGE', 'Community email change verification'), ('COMMUNITY_EMAIL_CHANGE_SECURITY', 'Community email change security notification')], default='COMMUNITY_ACTIVATION', max_length=50),
        ),
    ]
